### ISSUE TITLE
Capitolo 5 - Spiegazione dell'hype cycle

### ISSUE THREAD

**Issue by mzanella** [Augugrumi/GestioneImpreseInformaticheNotes#20]
**Description**
È corretto dire che `A questo punto la tecnologia sparisce dal mercato` nella parte discendete dell'hype cycle?

**Comment by Polpetta** [comment]
Penso che il prof intendesse che non se la caga più nessuno e diventa meno famosa, per poi essere ripresa più avanti appena escono le versioni di seconda/terza generazione che hanno un prezzo più basso e una migliore stabilità/rendimento

**Comment by mdipirro** [comment]
Secondo me detta così è un po' vago. Da un lato non ci sono prodotti _funzionanti_, ma dall'altro è proprio in questa fase, se non sbaglio, che gli investitori puntano sulle tecnologie in modo da cavalcare l'onda quando i prodotti iniziano a funzionare

**Comment by mzanella** [comment]
No esatto è proprio in questa fase in teoria è per quello che mi è venuto il dubbio sul "sparire dal mercato"... Che poi comunque la y è la visibilità che non è la stessa cosa che la presenza sul mercato, no?

**Comment by mdipirro** [comment]
Secondo me ni, nel senso che quando sei nel picco hai tanta visibilità, ma i prodotti che girano sono pochi (perché sono fatti ad-hoc, ecc, ecc), quindi la tecnologia non è altrettanto presente sul mercato.

**Comment by Polpetta** [comment]
@mzanella I tuoi dubbi sono stati risolti? La issue è chiudibile?
