### ISSUE TITLE
Setup Spellchecker

### ISSUE THREAD

**Issue by Polpetta** [Augugrumi/GestioneImpreseInformaticheNotes#7]
**Description**

**Other issues**

**Comment by mzanella** [comment]
Non riesco a fare andare lo spellchecker... Queste dovrebbero essere alcune delle parole nel documento
[no_dup.txt](https://github.com/Augugrumi/GestioneImpreseInformaticheNotes/files/1797431/no_dup.txt)

**Comment by mzanella** [comment]
Dovrebbe essere sistemato neii branch lezione0603 e lezione0703. Potrebbero esserci dei problemi nel merge per il dizionario scusa :sweat_smile:

**Comment by Polpetta** [comment]
Ma quelli ci saranno sempre i conflitti li. Sarebbe da fare come per `listOfSections` che viene generato dal make ma sinceramente mi sembra un sacco di lavoro per nulla. Tanto verso la fine le parole "straniere" saranno sempre quelle
